### ISSUE TITLE
安卓机上微信连续登录，会走取消登录的回调

### ISSUE THREAD

**Issue by bestsamcn** [wfxiaolong/ionic-plugin-damaiwechat#1]
你好，我在用你的插件做第三方登录，现在处于开发阶段，测试环境。qq登录没问题。就是微信登录，在连续的登录退出操作后，会出现执行“取消登录”的回调，而不是“成功登录”的回调，请问下这是为什么呢？

**Comment by wfxiaolong** [comment]
??? 可以具体一些吗？

**Comment by bestsamcn** [comment]
@wfxiaolong 好的,代码是这样的
`var _wechatLogin = function() {
            $$.loading.showNoBg();
            thirdPartyService.login('wechat', function(res) {
                $$.loading.hide();
                var obj = {};
                obj['snsopenkid'] = res.open_id;
                obj['accesstoken'] = res.access_token;
                obj['appid'] = 1;
                requestService.wechatLogin(obj).then(function(res) {
                    /*(1)正常登录回调*/
                    $$.toast('登录成功');

                    /*保存用户数据*/
                    $rootScope.globalData.userInfo['isLogin'] = true;
                    $rootScope.globalData.userInfo['userDetail'] = res.data;

                    /*本地缓存用户数据*/
                    localStorage['userIsLogin'] = true;
                    localStorage['loginUserDetail'] = JSON.stringify(res.data);

                     /*获取用户其他数据*/
                    userCommunity.getUserCommunity();
                    $scope.$emit('userloginEvent');
                    if(!localStorage['wechatShowSetMobile']){
                        _loginComfirm('是否绑定手机号码？');
                        localStorage['wechatShowSetMobile'] = true;
                        return false;
                    }
                    window.location='#/userCenter';
                })
            }, function(err) {
                 /*(2)如果连续登录退出的话,就可能出现执行这一步的代码,而非上一个function的代码*/
                $$.toast(err);
            })
        }`
上面的代码是微信登录的代码,如果我连续几次        登录后马上退出   的操作,就会出现走(2)这个回调,而非(1)的回调

**Comment by bestsamcn** [comment]
第一次代码评论,代码显示不好....

**Comment by bestsamcn** [comment]
![img_0320](https://cloud.githubusercontent.com/assets/17873080/20550563/ebc20ee2-b171-11e6-8545-6b2bce8b16eb.PNG)
![screenshot_2016-11-23-11-41-50](https://cloud.githubusercontent.com/assets/17873080/20550567/f394ecac-b171-11e6-819a-5c2676b15dc8.png)

还有就是安卓和ios上显示的效果不一致啊。这个问题怎么解决呢

**Comment by wfxiaolong** [comment]
友盟的SDK本来就是这样的

**Comment by wfxiaolong** [comment]
还有一种解决方式，就是自己画UI，然后调用暴露出来的接口...

**Comment by wfxiaolong** [comment]
关于你问的那个问题，安卓上的SDK集成我是找Android开发人员帮我开发的。
可能他的回调写得有问题...需要你那边自己修改java代码...iOS上有问题的话我还可以帮一下你。
不过年后不是都要支持https了...所以，这个项目也只是当作例子参考了。
